INSERT INTO VACATION.CREDENTIALS (EMAIL, PASSWORD) 
	VALUES ('vdeyneko@gmail.com', 'vd');
 INSERT INTO VACATION.USERS (LASTNAME, "NAME", CREDENTIALS_ID, USERGROUP_ID) 
	VALUES ('Виктор', 'Дейнеко', 1, 3);

INSERT INTO VACATION.CREDENTIALS (EMAIL, PASSWORD) 
	VALUES ('mmm@gmail.com', 'mmm');
 INSERT INTO VACATION.USERS (LASTNAME, "NAME", CREDENTIALS_ID, USERGROUP_ID) 
	VALUES ('Менский', 'Михаил', 2, 1);

INSERT INTO VACATION.CREDENTIALS (EMAIL, PASSWORD) 
	VALUES ('aaa@gmail.com', 'aaa');
 INSERT INTO VACATION.USERS (LASTNAME, "NAME", CREDENTIALS_ID, USERGROUP_ID) 
	VALUES ('Админов', 'Андрей', 3, 2);
