INSERT INTO VACATION.REQUESTSTATE (ID, "NAME", NEXTSTATE_ID, PREVIOUSSTATE_ID) 
	VALUES (1, 'StateForming', NULL, NULL);
INSERT INTO VACATION.REQUESTSTATE (ID, "NAME", NEXTSTATE_ID, PREVIOUSSTATE_ID) 
	VALUES (2, 'StateRequested', NULL, 1);
INSERT INTO VACATION.REQUESTSTATE (ID, "NAME", NEXTSTATE_ID, PREVIOUSSTATE_ID) 
	VALUES (3, 'StateApproved', NULL, 2);
INSERT INTO VACATION.REQUESTSTATE (ID, "NAME", NEXTSTATE_ID, PREVIOUSSTATE_ID) 
	VALUES (4, 'StateDisapproved', NULL, 2);

update VACATION.REQUESTSTATE set NEXTSTATE_ID = 2 where id = 1;
update VACATION.REQUESTSTATE set NEXTSTATE_ID = 3 where id = 2;
