INSERT INTO VACATION.MENUITEM (ID, LABELNAME, menuPath) 
	VALUES (1, 'user-management', 'userManagement');
INSERT INTO VACATION.MENUITEM (ID, LABELNAME, menuPath) 
	VALUES (2, 'vacation-request', 'requestList');
INSERT INTO VACATION.MENUITEM (ID, LABELNAME, menuPath) 
	VALUES (3, 'incoming-requests', 'requestListManager');
INSERT INTO VACATION.MENUITEM (ID, LABELNAME, menuPath) 
	VALUES (4, 'request-report', 'requestReport');
INSERT INTO VACATION.MENUITEM (ID, LABELNAME, menuPath) 
	VALUES (5, 'application-settings', 'appSettings');
INSERT INTO VACATION.MENUITEM (ID, LABELNAME, menuPath) 
	VALUES (6, 'user-change-password', 'userEdit?id=');


INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (1, 2);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (2, 1);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (2, 2);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (3, 1);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (3, 2);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (3, 3);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (3, 4);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (3, 5);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (1, 6);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (2, 6);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (3, 6);



