 INSERT INTO VACATION.USERGROUP (ID, BADMIN, BDEFAULT, BMANAGER, GROUPLABELNAME, GROUPSYSTEMNAME) 
	VALUES (1, 0, 1, 0, 'default-user-group', 'Пользователь');
INSERT INTO VACATION.USERGROUP (ID, BADMIN, BDEFAULT, BMANAGER, GROUPLABELNAME, GROUPSYSTEMNAME) 
	VALUES (2, 1, 0, 0, 'admin-user-group', 'Администратор');
INSERT INTO VACATION.USERGROUP (ID, BADMIN, BDEFAULT, BMANAGER, GROUPLABELNAME, GROUPSYSTEMNAME) 
	VALUES (3, 0, 0, 1, 'manager-user-group', 'Менеджер');
