INSERT INTO VACATION.MENUITEM (ID, LABELNAME, SERVLETPATH) 
	VALUES (1, 'user-management', 'userManagement');
INSERT INTO VACATION.MENUITEM (ID, LABELNAME, SERVLETPATH) 
	VALUES (2, 'vacation-request', 'requestList');
INSERT INTO VACATION.MENUITEM (ID, LABELNAME, SERVLETPATH) 
	VALUES (3, 'incoming-requests', 'requestManagementList');


INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (1, 2);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (2, 1);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (2, 2);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (3, 1);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (3, 2);
INSERT INTO VACATION.USERGROUP_MENUITEM (USERGROUP_ID, MENUITEMS_ID) 
	VALUES (3, 3);
